# need to figure out port mapping

apiVersion: apps/v1
kind: Deployment
metadata:
  name: process
  labels:
    app: process
spec:
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
    spec:
      containers:
      - name: process
        image: processor:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        imagePullPolicy: Never
        env:
        - name: minioAddr
          value: 192.168.0.101:9000
        - name: minioAccessKey
          value: admin
        - name: minioPW
          value: password
        - name: kafkaAddr
          value: 192.168.0.101:9092
        ports:
        - containerPort: 8081