# my global config
global:
  scrape_interval:     1s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: prometheus

  # scrape_interval is defined by the configured global (15s).
  # scrape_timeout is defined by the global default (10s).

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  - targets: ['localhost:9090', 'processor:8081']

